version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "src/main/frontend/package.json" }}
            - v2-dependencies-
      - run:
          name: buildSnapshottishDependencies
          command: |
            cd /tmp
            for proj in common wire actors cluster symbio symbio-jdbc lattice http; do
            git clone https://github.com/vlingo/vlingo-$proj.git
            cd vlingo-$proj
            mvn -DskipTests install
            cd ..
            done
      - run: mvn -B clean package -Pfrontend
      - persist_to_workspace:
          root: ~/project
          paths:
            - Dockerfile
            - target/
            - src/main/frontend/
            - src/test/e2e/
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - target/node
            - src/main/frontend/node_modules
          key: v2-dependencies-{{ checksum "src/main/frontend/package.json" }}
  e2e-test:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - v3-test-dependencies-{{ checksum "src/test/e2e/package.json" }}
            - v3-test-dependencies-
      - run:
          name: Get test dependencies
          command: |
            cd ~/project/src/test/e2e
            npm install
      - save_cache:
          paths:
            - src/test/e2e/node_modules
            - /home/circleci/.cache/Cypress
          key: v3-test-dependencies-{{ checksum "src/main/frontend/package.json" }}
      - run:
          name: Start server & run E2E tests
          command: |
            export VLINGO_SCHEMATA_PORT=9019
            java -jar ~/project/target/vlingo-schemata-*-jar-with-dependencies.jar env &
            export CYPRESS_BASE_URL=http://localhost:9019/app
            export API_URL=http://localhost:9019
            cd ~/project/src/test/e2e
            npm run test-multiple
      - store_test_results:
          path: src/test/e2e/multiple-results
      - store_artifacts:
          path: src/test/e2e/cypress/videos
          destination: videos
      - store_artifacts:
          path: src/test/e2e/cypress/screenshots
          destination: screenshots
  image:
    docker:
      - image:  circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker build . -t vlingo/vlingo-schemata
      - run: |
          echo "$DOCKER_TOKEN" | docker login --username $DOCKER_USER --password-stdin
          docker push vlingo/vlingo-schemata
workflows:
  version: 2
  default-workflow:
    jobs:
      - build
      - e2e-test:
          requires:
            - build
      - image:
          requires:
            - e2e-test
          filters:
            branches:
              only:
                - master


